-- ============================================================================
--  wf_subworkflow_field — บันทึกความหมายของทุกคอลัมน์ใน wf_sub_workflow_master
-- ============================================================================
--  CEO, 9 ก.ย. 2569: "ใน table ไม่ได้บอกไว้ อาจจะต้องหาที่เก็บว่า field ไหนใน
--  subworkflow ที่เกี่ยวกับคน หรือเกี่ยวกับอะไรบ้าง" -> "ต้องทำ table config เพิ่ม"
--
--  ตารางนี้ทำให้ทั้ง engine และหน้าจอ designer ถามได้ว่า "คอลัมน์ไหนพูดถึงคน
--  และไปหาคนจากตารางไหน" แทนที่ความรู้นั้นจะอยู่แต่ในหัวคนเขียนโค้ด
--
--  resolverKind: 16 คอลัมน์เรื่องคน ยุบเหลือ 4 วิธีหาคน
--    USER = ระบุตัวคน / ROLE = ระบุบทบาท / ORG = ตามผังองค์กร / LOA = ตามวงเงิน
--
--  รันซ้ำได้ (add-missing by fieldname) ไม่ทับค่าที่คนแก้ไว้แล้ว
-- ============================================================================

IF OBJECT_ID('wf_subworkflow_field','U') IS NULL
BEGIN
    CREATE TABLE wf_subworkflow_field (
        id           bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
        fieldname    nvarchar(100) NOT NULL,   -- ชื่อคอลัมน์จริงใน wf_sub_workflow_master
        category     nvarchar(50)  NOT NULL,   -- PERSON/STATUS/FLOW/CONDITION/SCREEN/RIGHT/TEXT/KEY/UNUSED
        label_th     nvarchar(200) NULL,
        label_en     nvarchar(200) NULL,
        describe     nvarchar(500) NULL,
        refTable     nvarchar(100) NULL,       -- PERSON: ไปหาคนจากตารางไหน
        resolverKind nvarchar(20)  NULL,       -- USER / ROLE / ORG / LOA
        sortorder    int NOT NULL DEFAULT 0,
        isactive     bit NOT NULL DEFAULT 1,
        moddate      datetime NULL,
        modby        nvarchar(100) NULL
    );
    CREATE UNIQUE INDEX UX_wf_subworkflow_field_name ON wf_subworkflow_field(fieldname);
END
GO

IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'iscustomUser') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'iscustomUser',N'PERSON',N'USER',N'wf_custom_user',N'ระบุตัวบุคคล',N'เลือกชื่อคนไว้ตรง ๆ จะเอาใครก็ได้ในขั้นนี้',10,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'iscustomRole') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'iscustomRole',N'PERSON',N'ROLE',N'wf_custom_role',N'ระบุตามบทบาท',N'ทุกคนที่มี role ที่ระบุไว้ เช่นส่งให้ฝ่าย HR ทั้งฝ่าย',20,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isLOA') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isLOA',N'PERSON',N'LOA',N'wf_loa_user',N'ตามวงเงิน (LOA)',N'Level of Authority: ใครมีสิทธิ์อนุมัติตามวงเงินของงาน',30,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'loacode') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'loacode',N'PERSON',N'LOA',N'wf_loa',N'รหัสวงเงิน',N'ใช้คู่กับ isLOA',31,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isupperrole') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isupperrole',N'PERSON',N'ORG',N'com_organization',N'หัวหน้าตามผัง (role)',N'เดินผังองค์กรจากหน่วยงานผู้ขอ หา approver_empid ไต่ parent_code ขึ้นไป',40,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isupperuser') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isupperuser',N'PERSON',N'ORG',N'com_organization',N'หัวหน้าตามผัง (user)',N'ทำงานเหมือน isupperrole ทุกประการ — เดินผังองค์กร',41,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isNeedsupervisorapprove') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isNeedsupervisorapprove',N'PERSON',N'ORG',N'com_organization',N'ผ่านหัวหน้ากี่ชั้น',N'จำนวนชั้นสายบังคับบัญชาที่ต้องอนุมัติก่อนผู้อนุมัติของขั้นนี้',42,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'verticalMaxLevel') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'verticalMaxLevel',N'PERSON',N'ORG',N'com_organization',N'ไต่ผังสูงสุดกี่ชั้น',N'ไต่ผังขึ้นไปได้ไม่เกินกี่ชั้น ชั้นที่ไต่ถึงจริงเป็นผู้ปิดงาน',43,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'empLevel') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'empLevel',N'PERSON',N'ORG',N'com_organization',N'ไต่ผังจำนวนชั้นตายตัว',N'ไต่ขึ้นกี่ชั้นแล้วไปต่อขั้นถัดไปตามปกติ',44,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isAdhocUser') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isAdhocUser',N'PERSON',N'USER',N'wf_adhoc_user',N'ผู้อนุมัติเฉพาะกิจ',N'ระบุคนเป็นราย ๆ ตอนงานวิ่งจริง ไม่ได้ตั้งไว้ล่วงหน้า',50,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isApproverSameOrg') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isApproverSameOrg',N'PERSON',N'ORG',N'Hremployee',N'คนในหน่วยงานเดียวกัน',N'พนักงานคนอื่นในหน่วยงานเดียวกับผู้ขอ',60,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isApproverSameCostCenter') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isApproverSameCostCenter',N'PERSON',N'ORG',N'Hremployee',N'คนใน Cost Center เดียวกัน',N'พนักงานคนอื่นที่ Cost Center เดียวกับผู้ขอ',61,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'userid1') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'userid1',N'PERSON',N'USER',N'sc_user',N'ผู้เกี่ยวข้องคนที่ 1',N'ระบุ userid ตรง ๆ บนขั้นนี้',70,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'userid2') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'userid2',N'PERSON',N'USER',N'sc_user',N'ผู้เกี่ยวข้องคนที่ 2',N'ระบุ userid ตรง ๆ บนขั้นนี้',71,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'userid3') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'userid3',N'PERSON',N'USER',N'sc_user',N'ผู้เกี่ยวข้องคนที่ 3',N'ระบุ userid ตรง ๆ บนขั้นนี้',72,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'iscustomApprover') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'iscustomApprover',N'PERSON',NULL,NULL,N'(สำรอง) ผู้อนุมัติกำหนดเอง',N'ยังไม่มีการใช้งานจริง',79,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'sitinstatus') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'sitinstatus',N'STATUS',NULL,NULL,N'สถานะเมื่องานมานั่งขั้นนี้',N'ตราลง job_master ตอนงานมาถึงขั้นนี้',100,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'standstatus') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'standstatus',N'STATUS',NULL,NULL,N'สถานะเมื่ออยู่กับที่',N'ยืนอยู่ขั้นเดิม ไม่ขยับ (Approve ที่ยังไม่ใช่ขั้นสุดท้าย)',101,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'forwardstatus') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'forwardstatus',N'STATUS',NULL,NULL,N'สถานะเมื่อเดินหน้า/อนุมัติจบ',N'ใช้เป็นสถานะปิดงานเมื่อ Approve ที่ขั้น istop',102,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'backwardstatus') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'backwardstatus',N'STATUS',NULL,NULL,N'สถานะเมื่อถอยหลัง',N'ตราเมื่อส่งกลับมาถึงขั้นนี้',103,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'approvedstatus') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'approvedstatus',N'STATUS',NULL,NULL,N'สถานะอนุมัติ',NULL,104,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'declinestatus') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'declinestatus',N'STATUS',NULL,NULL,N'สถานะไม่อนุมัติ',NULL,105,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'wlevel') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'wlevel',N'FLOW',NULL,NULL,N'ลำดับขั้น',N'ขั้นที่เท่าไหร่ในเส้นทาง 0 = ขั้นของผู้ขอ',200,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'istop') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'istop',N'FLOW',NULL,NULL,N'ขั้นสุดท้าย',N'ไม่มีที่ให้ไปต่อ อนุมัติที่ขั้นนี้คือจบงาน',201,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'backwardlevel') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'backwardlevel',N'FLOW',NULL,NULL,N'ตีกลับไปขั้นที่',N'ระบุขั้นปลายทางเมื่อถูกปฏิเสธ ว่างไว้ = ถอยทีละขั้น',202,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isandcondition') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isandcondition',N'CONDITION',NULL,NULL,N'ต้องอนุมัติร่วม (AND)',N'ต้องครบตามเกณฑ์ % ถึงจะผ่าน',300,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'andpercent') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'andpercent',N'CONDITION',NULL,NULL,N'เกณฑ์ % ที่ต้องผ่าน',NULL,301,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isorcondition') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isorcondition',N'CONDITION',NULL,NULL,N'คนใดคนหนึ่งพอ (OR)',NULL,302,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'iscondition') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'iscondition',N'CONDITION',NULL,NULL,N'มีเงื่อนไข',NULL,303,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isNeedBudgetApproval') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isNeedBudgetApproval',N'CONDITION',NULL,N'wf_budget',N'ต้องผ่านงบประมาณ',NULL,304,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isReturnSender') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isReturnSender',N'RIGHT',NULL,NULL,N'ส่งกลับหาผู้กรอกแบบฟอร์มได้',N'ติ๊ก = มีปุ่มส่งกลับถึงผู้สร้างงานเลย และแจ้งทุกคนที่เคยเกี่ยวข้อง / ไม่ติ๊ก = ส่งกลับได้ทีละขั้น',400,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isAutoApproveAllow') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isAutoApproveAllow',N'RIGHT',NULL,NULL,N'ข้ามอัตโนมัติถ้าไม่มีผู้อนุมัติ',NULL,401,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isPool') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isPool',N'RIGHT',NULL,NULL,N'งานกอง (Pool)',N'ใครในกลุ่มก็หยิบไปทำได้ ต้องกดรับงานก่อน',402,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isManualButton') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isManualButton',N'RIGHT',NULL,NULL,N'ปุ่มกำหนดเอง',N'ไม่ใช้ปุ่มมาตรฐาน ให้หน้าจอกำหนดเอง',403,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'controller') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'controller',N'SCREEN',NULL,NULL,N'หน้าเอกสาร (ดู)',N'route ของหน้าโมดูลที่จะเสียบในหน้า workflow เช่น /leave-requests/detail/{refid}',500,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'action') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'action',N'SCREEN',NULL,NULL,N'action ของหน้าเอกสาร',NULL,501,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'actionEdit') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'actionEdit',N'SCREEN',NULL,NULL,N'หน้าแก้ไขเอกสาร',N'ให้ผู้อนุมัติแก้ข้อความในแถวที่ส่งอนุมัติ',502,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'ApproveController') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'ApproveController',N'SCREEN',NULL,NULL,N'หน้าประกอบที่ 2',N'ข้อมูลประกอบให้ผู้อนุมัติดู เช่นยอดวันลาคงเหลือ',503,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'ApproveAction') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'ApproveAction',N'SCREEN',NULL,NULL,N'action ของหน้าประกอบ',NULL,504,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'displayName') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'displayName',N'SCREEN',NULL,NULL,N'ข้อความบนปุ่ม',N'เปลี่ยนคำว่า ส่งต่อ/อนุมัติ ให้ตรงกับงานจริง',505,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'isshow') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'isshow',N'SCREEN',NULL,NULL,N'แสดงขั้นนี้ในผัง',NULL,506,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'subject') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'subject',N'TEXT',NULL,NULL,N'ชื่อขั้น',NULL,600,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'describe') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'describe',N'TEXT',NULL,NULL,N'คำอธิบาย',NULL,601,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'subjectBiz') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'subjectBiz',N'TEXT',NULL,NULL,N'ชื่อขั้น (ฝั่งคู่ค้า)',NULL,602,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'describeBiz') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'describeBiz',N'TEXT',NULL,NULL,N'คำอธิบาย (ฝั่งคู่ค้า)',NULL,603,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'remark') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'remark',N'TEXT',NULL,NULL,N'หมายเหตุ',NULL,604,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'subject_en') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'subject_en',N'TEXT',NULL,NULL,N'ชื่อขั้น (EN)',NULL,610,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'describe_en') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'describe_en',N'TEXT',NULL,NULL,N'คำอธิบาย (EN)',NULL,611,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'subjectBiz_en') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'subjectBiz_en',N'TEXT',NULL,NULL,N'ชื่อขั้นคู่ค้า (EN)',NULL,612,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'describeBiz_en') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'describeBiz_en',N'TEXT',NULL,NULL,N'คำอธิบายคู่ค้า (EN)',NULL,613,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'subworkflowid') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'subworkflowid',N'KEY',NULL,NULL,N'รหัสขั้น',NULL,700,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'workflowid') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'workflowid',N'KEY',NULL,N'wf_workflow',N'รหัส workflow',NULL,701,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'wfcode') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'wfcode',N'KEY',NULL,NULL,N'รหัส workflow (ข้อความ)',NULL,702,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'status') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'status',N'UNUSED',NULL,NULL,N'(ไม่ได้ใช้)',N'bigint ที่ไม่มีโค้ดไหนอ่าน — คนละตัวกับ status ของ job',900,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'aa_id') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'aa_id',N'UNUSED',NULL,NULL,N'(ไม่ได้ใช้)',NULL,901,GETDATE());
IF NOT EXISTS (SELECT 1 FROM wf_subworkflow_field WHERE fieldname=N'aa_level') INSERT INTO wf_subworkflow_field (fieldname,category,resolverKind,refTable,label_th,describe,sortorder,moddate) VALUES (N'aa_level',N'UNUSED',NULL,NULL,N'(ไม่ได้ใช้)',NULL,902,GETDATE());
