using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Permissions;
using Microsoft.EntityFrameworkCore;

namespace LeaderDevelop.Model
{
    public class GoalTask
    {
        //public GoalTask() { }
        public GoalTask()
        {
            // Default StartDate to today and DayofGoal to 14 days
            Startdate = DateTime.Now;
             
        }


        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]  // Ensure that Id is auto-generated by the database
        public int Id { get; set; }


        [Required]
        [StringLength(250)]
        [Unicode(true)]
        [Display(Name = ("เป้าหมาย/Goal"))]
        public string Name { get; set; } = string.Empty;

        [Display(Name = ("วันที่เริ่ม/Start Date"))]
        public DateTime? Startdate { get; set; } = null;

        [Display(Name = ("วันที่สิ้นสุด/End Date"))]
        public DateTime? EndDate { get; set; } = null;



        // Adding validation to DayofGoal
        [Range(7, 14, ErrorMessage = "DayofGoal must be between 7 and 14 days.")]
        [Display(Name = ("ใช้เวลากี่วัน/Day Period"))]
        public double? DayofGoal { get; set; }


        [Display(Name = "ความก้าวหน้า/Progress")]
        [Range(0, 100, ErrorMessage = "ใส่ค่า 0-100 / Progress must be between 0 and 100.")]
        public decimal? progress { get; set; }


        //[Display(Name = ("ความก้าวหน้า/Progress"))]
        //public decimal? progress { get; set; }

        [StringLength(250)]
        [Unicode(true)]

        [Display(Name = ("อธิบายเพิ่มเติม/Description"))]

        public string Description { get; set; } = string.Empty;

        [StringLength(50)]
        [Unicode(true)]

        [Display(Name = ("เรื่อง/WOL"))]
        public string wol { get; set; } = string.Empty;

        [StringLength(500)]
        [Unicode(true)]
        [Display(Name = ("สิ่งที่ได้รับ/got idea"))]
        public string Lesson1 { get; set; } = string.Empty;

        [StringLength(500)]
        [Unicode(true)]
        [Display(Name = ("สิ่งที่ได้เรียนรู้/Learning"))]
        public string Lesson2 { get; set; } = string.Empty;


        [StringLength(500)]
        [Unicode(true)]
        [Display(Name = ("คำขอบคุณ/ThankFully"))]
        public string ThankFully { get; set; } = string.Empty;
        public int? UserId { get; set; }


        public int? coachId { get; set; }

        [StringLength(450)]
        [Unicode(true)]
        [Display(Name = ("ทีปรึกษา/Facililator"))]
        public string? facililatorID { get; set; } = string.Empty;

        // Add a nullable foreign key to WOL
        [Display(Name = "WOL ID")]
        public int? WolId { get; set; }

        // Navigation property for the WOL entity
        [ForeignKey("WolId")]
        public virtual WOL? WOL { get; set; }


        [Display(Name = ("ยกเลิก/Is Active"))]
        public bool IsActive { get; set; } = true;


        [StringLength(250)]
        [Unicode(true)]
        [Display(Name = ("ผู้แก้ไข/Modified By"))]
        public string? Modby { get; set; } = string.Empty;

        [StringLength(250)]
        [Unicode(true)]
        [Display(Name = ("ผู้สร้าง/Create By"))]
        public string? CreateBy { get; set; } = string.Empty;

        [Display(Name = ("วันที่สร้าง/Create Date"))]
        public DateTime CreateDate { get; set; } = DateTime.Now;

        [Display(Name = ("วันที่แก้/Modify Date"))]
        public DateTime ModDate { get; set; } = DateTime.Now;

         
        [Unicode(true)]
        [Display(Name = ("สถานะ/Status"))]
        public GoalTaskStatus? status { get; set; } = GoalTaskStatus.Active;


        [StringLength(450)]
        [Unicode(true)]
        [Display(Name = ("ผู้ตั้งเป้าหมาย/Goal By"))]
        public string? OwnerID { get; set; } = string.Empty;

        [StringLength(450)]
        [Unicode(true)]
        [Display(Name = ("email"))]
        public string? email { get; set; } = string.Empty;

        [InverseProperty("GoalTask")]
        //public virtual ICollection<Activity>? Activity { get; set; }
        public ICollection<Activity> Activity { get; set; } = new List<Activity>();


        public enum GoalTaskStatus
        {
            Active,
            Cancel,
            Success
        }

        // Method to calculate EndDate
        public void CalculateEndDate()
        {
            if (DayofGoal.HasValue)
            {
                //EndDate = (Startdate ?? DateTime.Now).AddDays((double)DayofGoal);
                //if (DayofGoal >= 7 && DayofGoal <= 14)
                //{
                    if (Startdate.HasValue)
                    {
                        EndDate = Startdate.Value.AddDays((double)DayofGoal).Date;

                    }
                    else
                    {
                        // Handle the case where StartDate is null (assign default value if needed)
                        EndDate = DateTime.Now.AddDays((double)DayofGoal).Date;// or any other default logic
                    }
                //}
            }
        }
    }

}

