// <auto-generated />
using HRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRM.Migrations
{
    // Hand-authored designer (attributes only); the authoritative model is
    // HRMContextModelSnapshot.cs, which carries this migration's changes.
    [DbContext(typeof(HRMContext))]
    [Migration("20260907100000_HrGapWave1AttendanceDeductionSalaryAdvance")]
    partial class HrGapWave1AttendanceDeductionSalaryAdvance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
#pragma warning restore 612, 618
        }
    }
}
