// <auto-generated />
using HRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRM.Migrations
{
    // Hand-authored designer (attributes only) — see
    // hrm_ef_migrations_must_be_hand_authored memory for why `dotnet ef
    // migrations add` is unsafe in this repo (pre-existing model/snapshot
    // drift generates a huge unrelated migration).
    [DbContext(typeof(HRMContext))]
    [Migration("20260907160000_AddVerticalMaxLevel")]
    partial class AddVerticalMaxLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
#pragma warning restore 612, 618
        }
    }
}
