// <auto-generated />
using HRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRM.Migrations
{
    // Hand-authored designer (attributes only); see the snapshot for the wave-3 model changes.
    [DbContext(typeof(HRMContext))]
    [Migration("20260907120000_HrGapWave3AttendanceQrCorrectionFlex")]
    partial class HrGapWave3AttendanceQrCorrectionFlex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
#pragma warning restore 612, 618
        }
    }
}
