// <auto-generated />
using HRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRM.Migrations
{
    // Hand-authored designer (attributes only) — see CLAUDE.md "EF Core migrations".
    [DbContext(typeof(HRMContext))]
    [Migration("20260922100000_OrgHeadsById")]
    partial class OrgHeadsById
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
