// <auto-generated />
using HRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRM.Migrations
{
    // Hand-authored designer (attributes only) — same convention as
    // 20260907140000_CvImportMenu.Designer.cs. The pre-existing model/DB
    // snapshot drift in this project (dead-scaffold DbSets like ALL_EMPLOYEE
    // that were never migrated) makes `dotnet ef migrations add` generate a
    // huge unrelated catch-up migration; this file intentionally skips a
    // full BuildTargetModel to avoid that, same tradeoff already accepted
    // elsewhere in this Migrations folder.
    [DbContext(typeof(HRMContext))]
    [Migration("20260907150000_AddScRolePosExecCode")]
    partial class AddScRolePosExecCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
#pragma warning restore 612, 618
        }
    }
}
