// <auto-generated />
using HRM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HRM.Migrations
{
    // Hand-authored designer: only the attributes are required for the runtime
    // (migration id + context). The full target-model copy that the tooling
    // normally emits here is omitted — the authoritative model is
    // HRMContextModelSnapshot.cs, which this migration's changes were folded into.
    [DbContext(typeof(HRMContext))]
    [Migration("20260906050000_PayrollPhaseABAndPayElementCatalog")]
    partial class PayrollPhaseABAndPayElementCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
#pragma warning restore 612, 618
        }
    }
}
